server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_hotel?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 8.130.88.119
    port: 5672
    username: admin
    password: admin
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo